package Clases;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class back_start extends javax.swing.JFrame {

    conexion cn;
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsm;
    DefaultTableModel dtm;
    
    
    
    
    public back_start() {
        //this.setLocationRelativeTo(this);
        getContentPane().setBackground(new java.awt.Color(69,140,146));
        initComponents();
        btnseeboys.setContentAreaFilled(false);
        btnadd.setContentAreaFilled(false);
        //btnseeregistro.setContentAreaFilled(false);
        btnseecitas.setContentAreaFilled(false);
        btnseetreatment.setContentAreaFilled(false);
        btnseeinformation.setContentAreaFilled(false);
        //btncard.setContentAreaFilled(false);
      
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Pictures/icon1.png"));


        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnadd = new javax.swing.JButton();
        btnseeboys = new javax.swing.JButton();
        btnseecitas = new javax.swing.JButton();
        btnseetreatment = new javax.swing.JButton();
        btnseeinformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER");
        setBackground(new java.awt.Color(69, 140, 146));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        btnadd.setBackground(new java.awt.Color(69, 140, 146));
        btnadd.setForeground(new java.awt.Color(69, 140, 146));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/addW.png"))); // NOI18N
        btnadd.setToolTipText("Add boy");
        btnadd.setBorderPainted(false);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnseeboys.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnseeboys.setForeground(new java.awt.Color(255, 255, 255));
        btnseeboys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/boys.png"))); // NOI18N
        btnseeboys.setToolTipText("See boys");
        btnseeboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseeboysActionPerformed(evt);
            }
        });

        btnseecitas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnseecitas.setForeground(new java.awt.Color(255, 255, 255));
        btnseecitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/citas.png"))); // NOI18N
        btnseecitas.setToolTipText("See appointment");
        btnseecitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseecitasActionPerformed(evt);
            }
        });

        btnseetreatment.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnseetreatment.setForeground(new java.awt.Color(255, 255, 255));
        btnseetreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/tratamiento.png"))); // NOI18N
        btnseetreatment.setToolTipText("See treatment");
        btnseetreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseetreatmentActionPerformed(evt);
            }
        });

        btnseeinformation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnseeinformation.setForeground(new java.awt.Color(255, 255, 255));
        btnseeinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/información.png"))); // NOI18N
        btnseeinformation.setToolTipText("Information personal");
        btnseeinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseeinformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnadd)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnseeboys, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnseecitas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnseetreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnseeinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnseeboys, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnseecitas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnseetreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnseeinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       info_patient see = new info_patient();
       see.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnseeboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseeboysActionPerformed
        // TODO add your handling code here:
        JFseeBoy see = new JFseeBoy ();
        see.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnseeboysActionPerformed

    private void btnseecitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseecitasActionPerformed
        SeeAppointment see = new SeeAppointment ();
        see.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnseecitasActionPerformed

    private void btnseeinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseeinformationActionPerformed
        seeInformation see = new seeInformation ();
        see.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnseeinformationActionPerformed

    private void btnseetreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseetreatmentActionPerformed
       info_tratamiento see = new info_tratamiento();
       see.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnseetreatmentActionPerformed

       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(back_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(back_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(back_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(back_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new back_start().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnseeboys;
    private javax.swing.JButton btnseecitas;
    private javax.swing.JButton btnseeinformation;
    private javax.swing.JButton btnseetreatment;
    // End of variables declaration//GEN-END:variables
}
