/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;    
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class info_tratamiento extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    back_start nuevo = new back_start();
    public info_tratamiento() {
        getContentPane().setBackground(new java.awt.Color(69,140,146));
        initComponents();
        mostrarDatos();
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Pictures/icon1.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFDosis = new javax.swing.JTextField();
        jTFpadecimiento = new javax.swing.JTextField();
        jTFtiempo = new javax.swing.JTextField();
        jTFfecha_inicio = new javax.swing.JTextField();
        jTFfecha_termino = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTreat = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTFIDM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFpatient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFIDT = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tratamiento");
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setName("inf_patient"); // NOI18N
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dosis");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de inicio");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tiempo");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Padecimiento");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de termino");

        jTFDosis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFDosis.setForeground(new java.awt.Color(69, 140, 146));
        jTFDosis.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFDosis.setName("nombre"); // NOI18N
        jTFDosis.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDosisActionPerformed(evt);
            }
        });

        jTFpadecimiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFpadecimiento.setForeground(new java.awt.Color(69, 140, 146));
        jTFpadecimiento.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFpadecimiento.setName("nombre"); // NOI18N
        jTFpadecimiento.setSelectionColor(new java.awt.Color(69, 140, 146));

        jTFtiempo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFtiempo.setForeground(new java.awt.Color(69, 140, 146));
        jTFtiempo.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFtiempo.setName("nombre"); // NOI18N
        jTFtiempo.setSelectionColor(new java.awt.Color(69, 140, 146));

        jTFfecha_inicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFfecha_inicio.setForeground(new java.awt.Color(69, 140, 146));
        jTFfecha_inicio.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFfecha_inicio.setName("nombre"); // NOI18N
        jTFfecha_inicio.setSelectionColor(new java.awt.Color(69, 140, 146));

        jTFfecha_termino.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFfecha_termino.setForeground(new java.awt.Color(69, 140, 146));
        jTFfecha_termino.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFfecha_termino.setName("nombre"); // NOI18N
        jTFfecha_termino.setSelectionColor(new java.awt.Color(69, 140, 146));

        btnOK.setBackground(new java.awt.Color(69, 140, 146));
        btnOK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        TableTreat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableTreat.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TableTreat);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Medicamento");

        jTFIDM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFIDM.setForeground(new java.awt.Color(69, 140, 146));
        jTFIDM.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFIDM.setName("nombre"); // NOI18N
        jTFIDM.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFIDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIDMActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Paciente");

        jTFpatient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFpatient.setForeground(new java.awt.Color(69, 140, 146));
        jTFpatient.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFpatient.setName("nombre"); // NOI18N
        jTFpatient.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpatientActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Tratamiento");

        jTFIDT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFIDT.setForeground(new java.awt.Color(69, 140, 146));
        jTFIDT.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFIDT.setName("nombre"); // NOI18N
        jTFIDT.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFIDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIDTActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnupdate.setText("Actualizar");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtras)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTFIDM, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFpadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFfecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFfecha_termino, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnupdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTFIDT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTFpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFpatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTFIDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFpadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFtiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFfecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFfecha_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDosisActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        PreparedStatement pt;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/tablas","root", "12345");
            pt = con.prepareStatement("INSERT INTO treatment(tratamient_id,namepatient,name_m,dose,suffering,duration,start_date,finish_date) VALUES (?,?,?,?,?,?,?,?)");
            pt.setString(1, jTFIDT.getText());
            pt.setString(2, jTFpatient.getText());
            pt.setString(3, jTFIDM.getText());
            pt.setString(4, jTFDosis.getText());
            pt.setString(5, jTFpadecimiento.getText());
            pt.setString(6, jTFtiempo.getText());
            pt.setString(7, jTFfecha_inicio.getText());
            pt.setString(8, jTFfecha_termino.getText());
            pt.executeUpdate();
            mostrarDatos();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    
    private void jTFIDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIDMActionPerformed

    private void jTFpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpatientActionPerformed

    private void jTFIDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIDTActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        nuevo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try
        {
            PreparedStatement pt = con.prepareStatement("UPDATE treatment SET namepatient ='"+jTFpatient.getText()+"', name_m='"+jTFIDM.getText()+"', dose='"+jTFDosis.getText()+"', suffering = '"+jTFpadecimiento.getText()+"', duration = '"+jTFtiempo.getText()+"', start_date = '"+jTFfecha_inicio.getText()+"', finish_date = '"+jTFfecha_termino.getText()+"'  WHERE tratamient_id='"+jTFIDT.getText()+"' ");
            pt.executeUpdate();
            mostrarDatos();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No es posible");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = TableTreat.getSelectedRow();
        if(fila >= 0)
        {
            jTFIDT.setText(TableTreat.getValueAt(fila, 0).toString());
            jTFpatient.setText(TableTreat.getValueAt(fila, 1).toString());
            jTFIDM.setText(TableTreat.getValueAt(fila, 2).toString());
            jTFDosis.setText(TableTreat.getValueAt(fila, 3).toString());
            jTFpadecimiento.setText(TableTreat.getValueAt(fila, 4).toString());
            jTFtiempo.setText(TableTreat.getValueAt(fila, 5).toString());
            jTFfecha_inicio.setText(TableTreat.getValueAt(fila, 6).toString());
            jTFfecha_termino.setText(TableTreat.getValueAt(fila, 7).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Filas no seleccionada");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = TableTreat.getSelectedRow();
        String cod = "";
        cod = TableTreat.getValueAt(fila, 0).toString();
        try
        {
            PreparedStatement pt = con.prepareStatement("DELETE FROM treatment WHERE tratamient_id ='"+cod+"'");
            pt.executeUpdate();
            mostrarDatos();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    void mostrarDatos()
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Tratamiento");
        modelo.addColumn("Paciente");
        modelo.addColumn("Medicamento");
        modelo.addColumn("Dosis");
        modelo.addColumn("Padecimiento");
        modelo.addColumn("Duracíón");
        modelo.addColumn("Inicio");
        modelo.addColumn("Termino");
        TableTreat.setModel(modelo);
        
       String []datos = new String[8]; 
       try{
           String sql = "SELECT * FROM treatment";
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/tablas","root", "12345");
           Statement st = con.createStatement();
           rs = st.executeQuery(sql);
           while(rs.next())
           {
               datos[0] = rs.getString(1);
               datos[1] = rs.getString(2);
               datos[2] = rs.getString(3);
               datos[3] = rs.getString(4);
               datos[4] = rs.getString(5);
               datos[5] = rs.getString(6);
               datos[6] = rs.getString(7);
               datos[7] = rs.getString(8);
               modelo.addRow(datos);
           }
           TableTreat.setModel(modelo);
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info_tratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info_tratamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTreat;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDosis;
    private javax.swing.JTextField jTFIDM;
    private javax.swing.JTextField jTFIDT;
    private javax.swing.JTextField jTFfecha_inicio;
    private javax.swing.JTextField jTFfecha_termino;
    private javax.swing.JTextField jTFpadecimiento;
    private javax.swing.JTextField jTFpatient;
    private javax.swing.JTextField jTFtiempo;
    // End of variables declaration//GEN-END:variables
}
