/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class seeInformation extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    back_start nuevo = new back_start();
    
    public seeInformation() {
        getContentPane().setBackground(new java.awt.Color(69,140,146));
        initComponents();
        mostrarDatos("");
        btnAtras.setContentAreaFilled(false);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Pictures/icon1.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFapellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFfechanacimiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFcurp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFnss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFsexo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFpeso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFaltura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFtiposangre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFalergias = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jTFantecedentes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableInf = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jTBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jTFID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jTFnombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFnombre.setForeground(new java.awt.Color(69, 140, 146));
        jTFnombre.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFnombre.setName("nombre"); // NOI18N
        jTFnombre.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");

        jTFapellido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFapellido.setForeground(new java.awt.Color(69, 140, 146));
        jTFapellido.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFapellido.setName("nombre"); // NOI18N
        jTFapellido.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Edad");

        jTFfechanacimiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFfechanacimiento.setForeground(new java.awt.Color(69, 140, 146));
        jTFfechanacimiento.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFfechanacimiento.setName("nombre"); // NOI18N
        jTFfechanacimiento.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CURP");

        jTFcurp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFcurp.setForeground(new java.awt.Color(69, 140, 146));
        jTFcurp.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFcurp.setName("nombre"); // NOI18N
        jTFcurp.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NSS");

        jTFnss.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFnss.setForeground(new java.awt.Color(69, 140, 146));
        jTFnss.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFnss.setName("nombre"); // NOI18N
        jTFnss.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo");

        jTFsexo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFsexo.setForeground(new java.awt.Color(69, 140, 146));
        jTFsexo.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFsexo.setName("nombre"); // NOI18N
        jTFsexo.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peso");

        jTFpeso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFpeso.setForeground(new java.awt.Color(69, 140, 146));
        jTFpeso.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFpeso.setName("nombre"); // NOI18N
        jTFpeso.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Altura");

        jTFaltura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFaltura.setForeground(new java.awt.Color(69, 140, 146));
        jTFaltura.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFaltura.setName("nombre"); // NOI18N
        jTFaltura.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Sangre");

        jTFtiposangre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFtiposangre.setForeground(new java.awt.Color(69, 140, 146));
        jTFtiposangre.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFtiposangre.setName("nombre"); // NOI18N
        jTFtiposangre.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alergias");

        jTFalergias.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFalergias.setForeground(new java.awt.Color(69, 140, 146));
        jTFalergias.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFalergias.setName("nombre"); // NOI18N
        jTFalergias.setSelectionColor(new java.awt.Color(69, 140, 146));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Antecedentes");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jTFantecedentes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFantecedentes.setForeground(new java.awt.Color(69, 140, 146));
        jTFantecedentes.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFantecedentes.setName("nombre"); // NOI18N
        jTFantecedentes.setSelectionColor(new java.awt.Color(69, 140, 146));

        TableInf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableInf.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(TableInf);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(69, 140, 146));
        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(69, 140, 146));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnShowAll.setBackground(new java.awt.Color(255, 255, 255));
        btnShowAll.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnShowAll.setForeground(new java.awt.Color(69, 140, 146));
        btnShowAll.setText("Mostrar todo");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jTFID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTFID.setForeground(new java.awt.Color(69, 140, 146));
        jTFID.setDisabledTextColor(new java.awt.Color(69, 140, 146));
        jTFID.setName("nombre"); // NOI18N
        jTFID.setSelectionColor(new java.awt.Color(69, 140, 146));
        jTFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIDActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(69, 140, 146));
        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnss, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtiposangre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFalergias, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFantecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShowAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtras)
                        .addGap(0, 417, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar)
                                .addComponent(btnShowAll))
                            .addComponent(btnAtras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFtiposangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFalergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFantecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombreActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        PreparedStatement pt;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/tablas","root", "12345");
            pt = con.prepareStatement("INSERT INTO patient(patient_id,name_patient,last_name,age,curp,nss,sexo,weight,height,blood,allergies,past) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            pt.setString(1, jTFID.getText());
            pt.setString(2, jTFnombre.getText());
            pt.setString(3, jTFapellido.getText());
            pt.setString(4, jTFfechanacimiento.getText());
            pt.setString(5, jTFcurp.getText());
            pt.setString(6, jTFnss.getText());
            pt.setString(7, jTFsexo.getText());
            pt.setString(8, jTFpeso.getText());
            pt.setString(9, jTFaltura.getText());
            pt.setString(10, jTFtiposangre.getText());
            pt.setString(11, jTFalergias.getText());
            pt.setString(12, jTFantecedentes.getText());
            pt.executeUpdate();
            mostrarDatos("");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        nuevo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrarDatos(jTBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        mostrarDatos("");
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = TableInf.getSelectedRow();
        if(fila >= 0)
        {
            jTFID.setText(TableInf.getValueAt(fila, 0).toString());
            jTFnombre.setText(TableInf.getValueAt(fila, 1).toString());
            jTFapellido.setText(TableInf.getValueAt(fila, 2).toString());
            jTFfechanacimiento.setText(TableInf.getValueAt(fila, 3).toString());
            jTFcurp.setText(TableInf.getValueAt(fila, 4).toString());
            jTFnss.setText(TableInf.getValueAt(fila, 5).toString());
            jTFsexo.setText(TableInf.getValueAt(fila, 6).toString());
            jTFpeso.setText(TableInf.getValueAt(fila, 7).toString());
            jTFaltura.setText(TableInf.getValueAt(fila, 8).toString());
            jTFtiposangre.setText(TableInf.getValueAt(fila, 9).toString());
            jTFalergias.setText(TableInf.getValueAt(fila, 10).toString());
            jTFantecedentes.setText(TableInf.getValueAt(fila, 11).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Filas no seleccionada");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try
        {
            PreparedStatement pt = con.prepareStatement("UPDATE patient SET name_patient='"+jTFnombre.getText()+"',last_name='"+jTFapellido.getText()+"',age='"+jTFfechanacimiento.getText()+"', curp='"+jTFcurp.getText()+"', nss = '"+jTFnss.getText()+"', sexo = '"+jTFsexo.getText()+"', weight = '"+jTFpeso.getText()+"', height = '"+jTFaltura.getText()+"', blood = '"+jTFtiposangre.getText()+"', allergies = '"+jTFalergias.getText()+"', past = '"+jTFantecedentes.getText()+"'  WHERE patient_id='"+jTFID.getText()+"' ");
            pt.executeUpdate();
            mostrarDatos("");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No es posible");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = TableInf.getSelectedRow();
        String cod = "";
        cod = TableInf.getValueAt(fila, 0).toString();
        try
        {
            PreparedStatement pt = con.prepareStatement("DELETE FROM patient WHERE patient_id ='"+cod+"'");
            pt.executeUpdate();
            mostrarDatos("");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No Eliminado");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIDActionPerformed
    
    void mostrarDatos(String valor)
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Edad");
        modelo.addColumn("CURP");
        modelo.addColumn("NSS");
        modelo.addColumn("Sexo");
        modelo.addColumn("Peso");
        modelo.addColumn("Talla");
        modelo.addColumn("Tipo de Sangre");
        modelo.addColumn("Alergias");
        modelo.addColumn("Antecedentes");
        TableInf.setModel(modelo);
        String sql = "";
        if(valor.equals(""))
        {
            sql = "SELECT * FROM patient";
        }
        else
        {
            sql = "SELECT * FROM patient WHERE patient_id = '"+valor+"'";
        }
        String []datos = new String[12]; 
       
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost/tablas","root", "12345");
           Statement st = con.createStatement();
           rs = st.executeQuery(sql);
           while(rs.next())
           {
               datos[0] = rs.getString(1);
               datos[1] = rs.getString(2);
               datos[2] = rs.getString(3);
               datos[3] = rs.getString(4);
               datos[4] = rs.getString(5);
               datos[5] = rs.getString(6);
               datos[6] = rs.getString(7);
               datos[7] = rs.getString(8);
               datos[8] = rs.getString(9);
               datos[9] = rs.getString(10);
               datos[10] = rs.getString(11);
               datos[11] = rs.getString(12);
               modelo.addRow(datos);
           }
           TableInf.setModel(modelo);
       }
       catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seeInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableInf;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFalergias;
    private javax.swing.JTextField jTFaltura;
    private javax.swing.JTextField jTFantecedentes;
    private javax.swing.JTextField jTFapellido;
    private javax.swing.JTextField jTFcurp;
    private javax.swing.JTextField jTFfechanacimiento;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFnss;
    private javax.swing.JTextField jTFpeso;
    private javax.swing.JTextField jTFsexo;
    private javax.swing.JTextField jTFtiposangre;
    // End of variables declaration//GEN-END:variables
}
